# Use standard Windows Server 2022 build VM
image: Visual Studio 2022

# Disable default MSBuild (.NET compilation)
build: off

# Environment Setup
install:
  - ps: Install-Product node 22 x64
  - npm install

# Build & Package Executable
test_script:
  - npm run dump
  - npm run app:dist

# Define Output Installer Artifact
artifacts:
  - path: dist\*.exe
    name: Windows-Setup-Installer
